### PR TITLE
Fixes #519: Knowledge Gap bug with semi-duplicate triples

### LINKED ISSUE #519: Fix bug in knowledge gap detection algorithm.
The problem can be reproduced via the `hvt-knowledge-network` and `human-knowledge-base` repositories. There we would like to instantiate the `human-knowledge-base` with the given knowledge gaps, but that does currently not work correctly.

### PR DESCRIPTION
**Pull request by Sophietje**
There's a bug in `getKnowledgeGaps()` where a gap is returned with two nearly-identical triples, e.g.: `?id hasCountry ?country` and `?id hasCountry Ireland`. We only want to keep the `?id hasCountry Ireland` in this case and ignore the triple with the additional variable.

### CODE REVIEW

File: smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+    private static final Logger LOG = LoggerFactory.getLogger(TestKnowledgeGapDetection.class);
+
+    private KnowledgeBaseImpl kbEggObserver;
+    private KnowledgeBaseImpl kbImperialEggSearcher;
+    private KnowledgeNetwork kn;
+    private PrefixMappingMem prefixes;
+    private AskKnowledgeInteraction askKI;
+    private Set<Rule> ruleSet;
+
+    @BeforeEach
```
Comment (bnouwt) [inline smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java:37]: I notice you are executing this `setup()` method `@BeforeEach` test method. Is that necessary? Because it makes the test quite a bit slower, I think. Or is it because some method create additional Knowledge Interactions that you do want lying around for subsequent tests?

File: smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+            Binding binding2 = new Binding();
+            binding2.put("id", "<https://www.tno.nl/example/ThirdImperial>");
+            binding2.put("image", "\"Picture of Third Imperial Fabergé Egg\"");
+            bindingSet.add(binding2);
+
+            return bindingSet;
+        });
+    }
+
+    @AfterEach
```
Comment (bnouwt) [inline smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java:194]: See `@BeforeEach` comment.

**Review by bnouwt — APPROVED** [review]
Hey @Sophietje, thanks for the changes 👍 I finished the review. Please do not consider the comments to be very important and feel free to choose to ignore them. I think it is useful to just mention most things that come up during a review although not all of them are equally relevant 😄

File: smart-connector/src/main/java/eu/knowledge/engine/smartconnector/impl/ReasonerProcessor.java [hunk 3]
```diff
@@ -711,40 +709,98 @@ public Set<KnowledgeGap> getKnowledgeGaps(RuleNode plan) {
...
 	}
 
+	/**
+	 * Given two triples, decides how they should be combined into a (single) knowledge gap
+	 * @return Action that should be taken when merging these two triples in a knowledge gap
+	 */
+	private static TripleMatchType getTripleMatchType(TriplePattern existingTriple, TriplePattern newTriple) {
+		Map<TripleNode, TripleNode> matches = existingTriple.findMatches(newTriple);
+		if (matches == null) {
+			return TripleMatchType.ADD_TRIPLE;
```
[the remark this answers is not in the document]
Comment (Sophietje) [reply smart-connector/src/main/java/eu/knowledge/engine/smartconnector/impl/ReasonerProcessor.java:736]: In this specific case I think I disagree. I'd prefer a clear `return` thus indicating end of this method for an (easy) case if it's at the beginning of a method, as opposed to needing to read the rest of the method to see whether anything else happens. I do agree that the return later on is less neat and I'll fix that.

File: smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java (hunk 1 above)
Comment (Sophietje) [reply smart-connector/src/test/java/eu/knowledge/engine/smartconnector/api/TestKnowledgeGapDetection.java:37]: Mostly that second part, this way it's clear which KIs are supposed to be part of which test case, not adding any unnnecessary clutter.
